backend:
  name: github
  repo: rosymingle/murundaka
  branch: main
  site_domain: murundaka.vercel.app
  base_url: https://murundaka.vercel.app
  auth_endpoint: oauth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Menu Label"
        name: "title"
        widget: "string"

      - label: "Hero Title"
        name: "heroTitle"
        widget: "string"

      - label: "Hero Tagline"
        name: "heroTagline"
        widget: "string"
        required: false

      - label: "Menu Order"
        name: "menuOrder"
        widget: "number"
        required: false
        default: 99

      - label: "Parent Menu"
        name: "parentMenu"
        widget: "string"
        required: false

      - label: "Page Content"
        name: "body"
        widget: "markdown"
