backend:
  name: github
  repo: rosymingle/murundaka
  branch: main
  site_domain: murundaka.vercel.app
  base_url: https://murundaka.vercel.app
  auth_endpoint: oauth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/home.md"
        fields:
          - label: "Menu Label"
            name: "title"
            widget: "string"
          - label: "Hero Title"
            name: "heroTitle"
            widget: "string"
          - label: "Hero Tagline"
            name: "heroTagline"
            widget: "string"
          - label: "Menu Order"
            name: "menuOrder"
            widget: "number"
            required: false
          - label: "Parent Menu"
            name: "parentMenu"
            widget: "string"
            required: false
          - label: "Page Content"
            name: "body"
            widget: "markdown"

      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - label: "Menu Label"
            name: "title"
            widget: "string"
          - label: "Hero Title"
            name: "heroTitle"
            widget: "string"
          - label: "Hero Tagline"
            name: "heroTagline"
            widget: "string"
          - label: "Menu Order"
            name: "menuOrder"
            widget: "number"
            required: false
          - label: "Parent Menu"
            name: "parentMenu"
            widget: "string"
            required: false
          - label: "Page Content"
            name: "body"
            widget: "markdown"
