backend:
  name: github
  repo: rosymingle/murundaka
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
